template_proj/basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('other/',views.other,name='other'),
    path('relative/',views.relative_url,name='relative'),
    path('register/',views.register,name='registeration'),
    path('login/',views.user_login,name='user_login'),
    path('logout/',views.user_logout,name='user_logout'),
]

template_proj/template_proj/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls,name='admin'),
    path('',views.index,name='index'),
    path('basic_app/',include('basic_app.urls')),
]

template_proj/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.DO_NOTHING)
    portfolio_site = models.URLField(blank = True)
    profile_pic = models.ImageField(upload_to = 'profile_pics',blank = True)

    def __str__(self):
        return self.user.username

template_proj/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget = forms.PasswordInput())

template_proj/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm,UserProfileInfoForm,LoginForm

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request,'basic_app/index.html')

def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data = request.POST)
        userprofile_form = UserProfileInfoForm(data = request.POST)

        if user_form.is_valid() and userprofile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            user_profile = userprofile_form.save(commit = False)
            user_profile.user = user

            if 'profile_pic' in request.FILES:
                user_profile.profile_pic = request.FILES['profile_pic']

            user_profile.save()
            registered = True

        else:
            print(user_form.errors,userprofile_form.errors)
    else:
        user_form = UserForm()
        userprofile_form = UserProfileInfoForm()
    return render(request,'basic_app/registeration.html',{'user_form':user_form,'profile_form':userprofile_form,'registered':registered})

def user_login(request):

    if request.method == 'POST':
        login_form = LoginForm(data = request.POST)
        if login_form.is_valid():
            username = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']
            user = authenticate(username = username,password = password)
            if user:
                if user.is_active:
                    login(request,user)
                    return HttpResponseRedirect(reverse('index'))
                else:
                    return HttpResponse('User not active')
            else:
                print('some malicious user tried to login')
                print('username:{} and password: {}'.format(username,password))
                return HttpResponse('Invalid Login Details')
    else:
        login_form = LoginForm()
    return render(request,'basic_app/login.html',{'login_form':login_form})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def other(request):
    return render(request,'basic_app/other.html')

def relative_url(request):
    return render(request,'basic_app/relative_url.html')

template_proj/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
      <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
          <ul class="nav navbar-nav">
            <li class="navbar-brand"><a href="{% url 'index' %}">BRAND</a></li>
            <li class="navbar-link"><a href="{% url 'admin:index' %}">Admin</a></li>
            <li class="navbar-link"><a href="{% url 'basic_app:registeration' %}">Register</a></li>
            {% if user.is_authenticated %}
            <li class="navbar-link"><a href="{% url 'basic_app:user_logout' %}">Logout</a></li>
            {% else %}
            <li class="navbar-link"><a href="{% url 'basic_app:user_login' %}">Login</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>
      <div class="container">
        {% block body_block %}
        {% endblock %}
      </div>
  </body>
</html>

template_proj/templates/basic_app/index.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% block body_block %}
    <div class="jumbotron">
      <h1>Welcome to the index page</h1>
    </div>
{% endblock %}

template_proj/templates/basic_app/login.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% block body_block %}
<h1>Welcome to the Login Page</h1>
<div class="jumbotron">
  <form action="{% url 'basic_app:user_login' %}" method="POST">
    {{login_form.as_p}}
    {% csrf_token %}
    <input class ="btn btn-success" type="submit" value="Login">
  </form>
</div>
{% endblock %}

template_proj/templates/basic_app/other.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% block body_block %}
    <h1>Welcome to the other page</h1>
{% endblock %}

template_proj/templates/basic_app/registeration.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% block body_block %}
<div class="jumbotron">
  <h1>Welcome to the registeration page</h1>
  {% if registered %}
  <h2>Thank you registering!</h2>
  {% else %}
  <h2>Register Here</h2>
  <form method="POST" enctype="multipart/form-data">
    {{user_form.as_p}}
    {{profile_form.as_p}}
    {% csrf_token %}
    <input class ="btn btn-success" type="submit" value="Register">
  </form>
  {% endif %}
</div>
{% endblock %}

template_proj/templates/basic_app/relative_url.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Relative Url</title>
  </head>
  <body>
    <h1>Welcome to the relative url page</h1>
    <a href="{% url 'basic_app:other' %}">Link to the other page</a>
    <a href="{% url 'admin:index' %}">Link to the admin page</a>
    <a href="{% url 'index' %}">Link to the index page</a>
  </body>
</html>